name: Run Python Tests
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Run pylint
        run: pylint *.py
      - name: Run tests with pytest
        run: pytest tests