name: Run Python Tests
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use "3.9"
          poetry install --no-interaction
      - name: Run linting
        run: poetry run make lint
      - name: Run tests
        run: poetry run make test
