name: Run Python Tests
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.11 pylint==2.11.1 pytest==6.2.5
          poetry install
      - name: Run pylint
        run: poetry run pylint --fail-under=6 *.py
      - name: Run tests
        run: poetry run pytest tests